title: Trying out new site
author: Mariam
email: mariam@mariam.com
description: > # this means to ignore newlines until "baseurl:"
  Trying to build a github page and this could be fun.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
